### PR TITLE
Add bracket to coffee koa and kob snippets

### PR DESCRIPTION
**Pull request by linc01n**

### CODE REVIEW

**Comment by jasonm23** [comment]
Go ahead and do a normal merge / rebase to master on this one

**Comment by linc01n** [comment]
Should we remove `.yas-compiled-snippets.el` and put it in `.gitignore`?

I can see `/Users/jason/` in it and it fails when I try to use `yas-visit-snippet-file`.

**Comment by jasonm23** [comment]
Yes

**Comment by linc01n** [comment]
Merged

**Pull request closed without merging**
